// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmiL4mXXPTcnVdkmKOZr5F6CoqKLxQ8tE',
    appId: '1:1004970733902:web:79adf0f29ef4589d052e1f',
    messagingSenderId: '1004970733902',
    projectId: 'marcat-jo',
    authDomain: 'marcat-jo.firebaseapp.com',
    storageBucket: 'marcat-jo.firebasestorage.app',
    measurementId: 'G-PJC7J2ED4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqktAJyl7bOvmY-Q6YGyCPC_L1wJQXK8Y',
    appId: '1:1004970733902:android:4cf1b865d30a309e052e1f',
    messagingSenderId: '1004970733902',
    projectId: 'marcat-jo',
    storageBucket: 'marcat-jo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB04-XFhBrouVqPvEb7alyGB4pGQ0bsnog',
    appId: '1:1004970733902:ios:79b25a3a9ec31909052e1f',
    messagingSenderId: '1004970733902',
    projectId: 'marcat-jo',
    storageBucket: 'marcat-jo.firebasestorage.app',
    iosBundleId: 'com.arandas.marcat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmiL4mXXPTcnVdkmKOZr5F6CoqKLxQ8tE',
    appId: '1:1004970733902:web:37d55591e74ae9e1052e1f',
    messagingSenderId: '1004970733902',
    projectId: 'marcat-jo',
    authDomain: 'marcat-jo.firebaseapp.com',
    storageBucket: 'marcat-jo.firebasestorage.app',
    measurementId: 'G-1RKNBLH9HK',
  );
}
